name: "Heather"
description: "A Hyperminimal Jekyll Theme"
author: "Jxnblk"
baseurl: /blog

#url: "http://localhost:4000"
#url: "http://jxnblk.github.io/Heather"

exclude: [README.md, Rakefile]
paginate: 16
permalink: /:title
