name: "Coders Blog"
description: "Stardate 2014.  I've never trusted Klingons."
author: "svensvan"

#url: "http://localhost:4000"
#url: "http://localhost:4000"
#url: "http://jxnblk.github.io/Heather"
url: "http://svensvan.github.io/blog"

exclude: [README.md, Rakefile]
paginate: 16
permalink: /:title
